<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-0BD3UPIP" failures="1" tests="5" name="SmokeTest" time="13.608" errors="0" timestamp="07 Jun 2025 17:20:21 GMT">
  <testcase classname="swaglab_test.LoginTest" name="LockedUserLoginFailureTest" time="0.272"/>
  <testcase classname="swaglab_test.LoginTest" name="LoginFailureTestFromExcel" time="0.284"/>
  <testcase classname="swaglab_test.LoginTest" name="LoginFailureTestFromProperties" time="0.297"/>
  <testcase classname="swaglab_test.LoginTest" name="LoginSuccessTest" time="0.318"/>
  <testcase classname="swaglab_test.LoginTest" name="LoginFailureTest" time="0.277">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Username and password do not match any user in this services] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Username and password do not match any user in this services] but found [Epic sadface: Username and password do not match any user in this service]
at swaglab_test.LoginTest.LoginFailureTest(LoginTest.java:42)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginFailureTest -->
</testsuite> <!-- SmokeTest -->
